### ISSUE TITLE
Clarification about art assets licensing

### ISSUE THREAD

**Issue by akien-mga** [WinterLicht/Chaos-Projectile#1]
Hi there,

First of all congratulations for this nice game, I found it by chance while browsing GitHub and it feels really great :)

According to [doc/source/README.rst](doc/source/README.rst), the art assets have no specific license, it is just stated that they are copyrighted by their creators listed in the credits file.

Could you add a clarification to whether those assets are effectively nonfree, as the current lack of licensing suggests, and if so state in which conditions the assets can be redistributed (e.g. allowed to be redistributed with the Chaos Projectile game).
Better yet would be to license them under a free license like a Creative Commons license (e.g. CC BY-SA 4.0 or CC BY 4.0), but that's your call :)

**Comment by WinterLicht** [comment]
Thank You for Your interest in our game! Your feedback is very much appreciated. =)
We will have a closer look into definitions of licenses and update the license soon.

**Comment by Deevad** [comment]
Hi, good looking project. I was seduced by the quality of the screenshot on the README page.

@WinterLicht : Here is the definitions of licenses compatibility with GPL you are looking for:  http://www.gnu.org/licenses/license-list.en.html  ( ctrl+f to search for 'creative common' threw the page, big page ) In a nutshell : CC-By is Ok , CC-By-Sa is problematic depending the version (last one is ok), Nc and Nd tag are not compatible with GNU GPL.

What con non GPL artwork does: 
- the game can't be packaged for most linux distributions package manager.
- the game can't be bundled in commercial magazine CD, or hosted on website with Adv.
- It's not encouraging user like me to fork or propose contrib for the project, well... because I prefer invest itme into full open-source projects.

What pros it has:
- Artist's artworks can't be reused into an external commercial game dev project.
- Artist's artworks can't be sold into website proposing big library of assets.
- Full game is protected this way against commercial usage.

The final choice is in your hands (and in the hands of the artist) and I respect any license decisions.

**Comment by Funatiker** [comment]
> the game can't be bundled in commercial magazine CD, or hosted on website with Adv.

That's not a con but the main reason why the art assets are released under NC-conditions: Extreme right wing magazine publishers should be allowed to sell the game (on a DVD with the magazine) without asking for permission.

About hosting on a website with advertisement: That's okeh. The commercial website can just link to GitHub.

About the forking issue: Everybody is free to create own assets for a commercial-enabled fork.

The bigger issue is the still undecided license for the sound files.

**Comment by Deevad** [comment]
Ok, thanks for replying with details @Funatiker .

**Comment by Funatiker** [comment]
@Deevad I hope we haven't totally scared you by being not GPL-compatible. We'd still appreciate your contribution. Maybe you want to contribute a level, figure out the bug about the owner-less projectiles, enable compatibility with newer versions of pyscroll and so on …

**Comment by Deevad** [comment]
@Funatiker : Not scared ; just not interested as a potential contributor/forker as it is now: I have small webcomic open-project ( http://www.peppercarrot.com/ ) and I'm always looking full CC-By and GPL projects around; especially a video-game (in my scope: Godot, HTML5, or Python/Pygame) I could adapt to Pepper&Carrot with easy split of code and asset in the directory structure to keep update with the main master branch. The base GPL code here with Chaos-Projectile is attractive, but redoing all the gfx as a starting point for a dedicated full open project is too much work for me alone.

**Comment by WinterLicht** [comment]
Hi, I'm responsible for art assets (and code).
The NC-license was simply chosen because it sounded most beneficial. But I didn't know it's incompatible, 'cause of not enough research... The game should be of course GPL compatible in the first place!

@Deevad thank you very much for the simple explanation, advise and the link. Also thanks for showing interest!

@Funatiker what are "owner-less projectiles"? Maybe you can recreate the situation/bug and open a new issue?

**Comment by Funatiker** [comment]
GPL-incompatible just means that you can't put the whole project under GPL if you want to maintain the NC-status.

@WinterLicht About the owner-less projectile: It's the bug we've already tried to hunt at FrOSCon: An enemy shoots a projectile while dying. The projectile remains on the screen forever while the enemy has already been dead for a while. I put some screenshots in #9.

**Comment by Deevad** [comment]
Thank you @WinterLicht for opening the license of assets in commit https://github.com/WinterLicht/Chaos-Projectile/commit/ec0325cbfbf35ff96b0a06b7b7820bd9b5292587 ! I will 'git clone' it this week and try to make it work on my local computer. Then I'll explore it. Consider this bug #1 fixed!

**Comment by akien-mga** [comment]
Excellent, thanks a lot. I'll see if I can package Chaos Projectile for my distro now that the assets are packaging-friendly (previously the NC clause would make assets "nonfree" for many Linux distributions - which doesn't prevent packaging them in a nonfree repo, but has lower priority compared to 100% libre projects).

**Comment by Funatiker** [comment]
@akien-mga be aware that the project is still non-free as the sound files have no license yet. So this bug is not fixed yet. Furthermore, CC-By allows usage in non-free projects which I believe not to be intended by @WinterLicht.

**Comment by akien-mga** [comment]
@Funatiker It looks like the sounds were removed in ec0325cb, or are there more of them?

Regarding the graphics license, it's indeed important to be aware of the implications of the various existing CC licenses when choosing one.

CC By does allow usage of the art in non-free projects, though CC By-NC-SA allows it too; the only differences are that it restricts usage in commercial projects (which could be libre or not, though it's true that often commercial projects are proprietary, while libre projects are gratis - but that's not inherent to their licenses, more to their respective cultures), and enforces that derivative works should be under a compatible license. This last point is kind of a grey area AFAIK, as the license does not state clearly what constitutes a derivative work: one can interpret it as "a derivative digital or printed asset based on the original work", but it's hard to define if a game that uses the asset without modifying it constitutes a derivative work or not.

So if the primary motivation is to prevent people from making proprietary games with these assets, I think CC By-SA (without the NC clause) is a good choice. Due to the legal grey area I pointed out, proprietary game developers are wary of the SA clause, so they probably wouldn't use the assets this way. The lack of the NC clause means that people could make libre games using those assets and sell them; one could even actually sell Chaos Projectile without being the upstream developer. That's something most popular free software games have to deal with (SuperTuxKart, Flight Gear, etc.), but in the end there is not much harm done.

On the other hand _not_ using the NC clause means that the assets are fully libre, so they can benefit the free software and libre games community as a whole. The game can be packaged in Linux distributions, and the By-SA clauses ensure that the assets will stay under an open license, and that the author will always be rightfully credited for their work.

Sorry if I stated the obvious, just wanted to provide a bit more context on this topic.

**Comment by Funatiker** [comment]
@akien-mga You are right, the current sate of the repository is free as the sounds are disabled and removed. However, I consider the sounds to be a part of the project. I think it is a work-around to exclude the sounds. The adaptive sound-system is a vital part of the gameplay and the best solution would be to get free sounds or clarify the license of the soundfiles that were removed.

When I talked about non-free projects, I didn't refer to the NC-clause but to the lack of the SA-clause. You are totally right. CC-BY-SA would be the perfect compromise as it allows redistribution in libre repositories but still prevents non-free remixes/derivatives. However, the currently stated license is only CC-BY which is the complete opposite of what was intended.

**Comment by Deevad** [comment]
https://creativecommons.org/licenses/by-sa/4.0/
In CC-By-Sa, the 'Sa' rules is to " _ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original._ "
You can still do commercial usage, derivation, etc. The only obligation is to distribute the transformed source to the public under a similar license (so,it's recursive).

[edited: typo]

**Comment by Funatiker** [comment]
@Deevad exactly. For CC-By-Sa-licensed work, you are obligated to keep the license which means that it cannot be used in non-free-as-in-freedom projects but it can be used in non-free-as-in-free-beer projects provided that they are free-as-in-freedom.

**Comment by Deevad** [comment]
@Funatiker  Ah, yes. the double usage of 'free' in English is confusing (free-as-in-free-beer and free-as-in-freedom). We should probably use 'gratuitous' and 'libre' in this type of discution  xD

**Comment by WinterLicht** [comment]
The game _was intended_ under a GPL-License. Yes, the assets are CC-BY now.
Sounds are removed, 'cause there is no clear license at the moment. It's not a work-around. They may return.

Thanks for waking up ChaosProjectile from hibernation, license information and your interest!

PS: Please update me, if ChaosProjectile or parts of it is used in your Linux-distro, project etc.

**Comment by Funatiker** [comment]
@WinterLicht You can release the source-code under GPL and the art-assets under any other license. When we said "GPL-incompatible", we meant that the art-asset can't be re-licensed under GPL as long as they have the NC-flag.

And yes, I am aware that the game is _intended_ under a GPL-License but CC-BY is exactly the opposite of GPL: CC-BY does not have the copy-left option which GPL does have.

So what you need is _not_ CC-BY but CC-BY-SA!
