### ISSUE TITLE
activate default controll settings on default

### ISSUE THREAD

**Issue by iudex-** [WinterLicht/Chaos-Projectile#12]
just starting the game and clicking "use this settings and play" doesn't work because the default settings are not enabled by default.

isn't the purpose of the defaults to be the default? :confused: 

![unbenannt](https://cloud.githubusercontent.com/assets/56843/22088172/6d1b448a-dde2-11e6-9323-e97877c577c4.png)

btw, liebe Grüße :grinning:

**Comment by WinterLicht** [comment]
Default settings are set to "yes" on game start. Also updated executables.
( ^▽ ^ )ﾉ liebe Grüße zurück!
