### ISSUE TITLE
Spikes deadliness

### ISSUE THREAD

**Issue by iudex-** [WinterLicht/Chaos-Projectile#3]
Spikes (type=deadly) only kill the player, not enemies.
This looks kind of strannge

![](http://i.imgur.com/fZxIXIg.png)

**Comment by WinterLicht** [comment]
Hi,
Yes, spikes do not kill enemies.

On collision with "deadly" tiles, enemies behave the same way as they would, when they collide with "corner". Also, they simply change movement direction.

**Comment by Funatiker** [comment]
In the normal game play, enemies wouldn't touch deadly tiles. They just avoid them.

**Comment by iudex-** [comment]
The screenshot shows "normal gameplay". The enemie jumped down a cliff and lived happily ever after on the spikes.

**Comment by Funatiker** [comment]
Sorry for the inconvenience. I misunderstood @WinterLicht. She meant that the non-jumping enemies would not leave their platforms, Jumpers however might do this if it is the only way to follow you. But she said that killing enemies by attracting them to deadly tiles is not intended. Her philosophy is that those areas are their home and thus not deadly to them.

**Comment by WinterLicht** [comment]
It is simply a design decision. I don't want to exclude level parts with adjacent spikes and regular platforms:
```
         +-----------+
         |   ENEMY   |
         |           |
         | MOVEMENT  |
         | <-- LEFT  |
         +-----------+
+-----------++-----------++-----------+
|           ||           ||           |
|  DEADLY   ||  REGULAR  ||  REGULAR  |
|   TILE    ||   TILE    ||   TILE    |
|           ||           ||           |
+-----------++-----------++-----------+
```
The enemy is just colliding with a spike tile. If it would be deadly, than he would instantly die. But it is not and an enemy is inverting his movement direction on collision.
